(function(root){
  'use strict';
  const digits=s=>String(s==null?'':s).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace('٫','.').replace(/[,٬،]/g,'');
  const num=v=>{const n=parseFloat(digits(v));return Number.isFinite(n)?Math.max(0,n):0};
  const geom=r=>{const L=num(r.L),W=num(r.W),H=num(r.H),per=2*(L+W),gross=per*H,open=num(r.dn)*num(r.dw)*num(r.dh)+num(r.wn)*num(r.ww)*num(r.wh);return {floor:L*W,ceiling:L*W,wall:Math.max(0,gross-open),gross,open,per,vol:L*W*H,over:open>gross&&gross>0};};
  function itemQty(room,item,product,wastePercent){const g=geom(room),n=Math.max(1,num(room.n)||1),on=['floor','wall','ceiling'].includes(item.on)?item.on:(product.surf|| (product.mode==='vol'?'floor':'wall')),w=wastePercent==null?null:num(wastePercent);if(product.mode==='area'){const per=num(item.per==null?product.perM2:item.per);return per>0&&w!=null?g[on]*n*per*(1+w/100):null;}if(product.mode==='vol'){const th=num(item.th==null?product.def:item.th);return th>0&&w!=null?g[on]*n*th/100*(1+w/100):null;}return item.q==null||String(item.q).trim()===''?null:num(item.q)*n;}
  function calcRun(k,v){const wasteProvided=String(v.w==null?'':v.w).trim()!=='';const w=wasteProvided?1+num(v.w)/100:null,o=[];if(k==='floor'){const A=num(v.A),T=num(v.T),vol=A*T/100,volW=wasteProvided?vol*w:null;if(A&&T&&wasteProvided){o.push({l:'حجم سبکدانه (با ضایعات)',v:volW,u:'متر مکعب',add:1});if(num(v.bag)){const bags=Math.ceil(volW*1000/num(v.bag));o.push({l:'تعداد کیسه',v:bags,u:'کیسه',add:1},{l:'مازاد حجمی',v:bags*num(v.bag)-volW*1000,u:'لیتر'});}}if(A&&T&&num(v.dl)){const wl=vol*num(v.dl);o.push({l:'وزن لایه‌ی سبک',v:wl,u:'کیلوگرم'},{l:'بار مرده‌ی سبک',v:T/100*num(v.dl),u:'kg/m²'});if(num(v.dt)){const wt=vol*num(v.dt);o.push({l:'وزن با مصالح سنتی',v:wt,u:'کیلوگرم'},{l:'کاهش بار مرده',v:wt-wl,u:'کیلوگرم'},{l:'کاهش نسبی',v:(wt-wl)/wt*100,u:'٪'},{l:'کاهش بار روی سطح',v:(wt-wl)/A*9.80665/1000,u:'kN/m²'});}}}else if(k==='block'){const net=Math.max(0,num(v.A)-num(v.o)),j=num(v.j)/10,bl=num(v.bl),bh=num(v.bh),bt=num(v.bt);if(net&&bl&&bh){const n0=net/(((bl+j)/100)*((bh+j)/100));o.push({l:'مساحت خالص دیوار',v:net,u:'متر مربع'});if(wasteProvided&&String(v.j==null?'':v.j).trim()!=='')o.push({l:'تعداد بلوک (با ضایعات)',v:Math.ceil(n0*w),u:'عدد',add:1},{l:'مازاد بلوک',v:Math.ceil(n0*w)-n0,u:'عدد'},{l:'بلوک در هر م²',v:n0/net,u:'عدد'});if(bt&&wasteProvided&&String(v.j==null?'':v.j).trim()!==''){const mv=Math.max(0,net*bt/100-n0*bl*bh*bt/1e6)*w;o.push({l:'حجم ملات (با ضایعات)',v:mv,u:'متر مکعب',add:1},{l:'حجم ملات',v:mv*1000,u:'لیتر'});}}}else{if(num(v.A)&&num(v.t)&&num(v.ref)&&wasteProvided){const kg=num(v.A)*num(v.t)/10*num(v.ref)*w;o.push({l:'وزن گچ (با ضایعات)',v:kg,u:'کیلوگرم'});if(num(v.bag)){const bags=Math.ceil(kg/num(v.bag));o.push({l:'تعداد کیسه',v:bags,u:'کیسه',add:1},{l:'مازاد وزن',v:bags*num(v.bag)-kg,u:'کیلوگرم'});}}if(num(v.Ap)&&num(v.pw)&&num(v.ph)&&wasteProvided){const net=Math.max(0,num(v.Ap)-num(v.po)),n=Math.ceil(net/(num(v.pw)*num(v.ph))*w);o.push({l:'تعداد پانل',v:n,u:'عدد',add:1},{l:'مساحت پانل (با ضایعات)',v:net*w,u:'متر مربع',add:1},{l:'مازاد پانل',v:n*num(v.pw)*num(v.ph)-net*w,u:'متر مربع'});}}return o;}
  function roundToSalesUnit(quantity, packSize){const q=Number(quantity),p=Number(packSize);if(!Number.isFinite(q)||q<0||!Number.isFinite(p)||p<=0)return {units:null,roundedQuantity:null,surplus:null};const units=Math.ceil(q/p);return {units,roundedQuantity:units*p,surplus:units*p-q};}
  const api={num,geom,itemQty,calcRun,roundToSalesUnit};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;root.RavaqCalcCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
